package toolchainmastery
//go:build ignore























































































































































































































































































































































}	fmt.Println()	fmt.Println("  Confinement → don't share (best option!)")	fmt.Println("  Channel → communicate between goroutines")	fmt.Println("  Atomic → simple counters/flags")	fmt.Println("  Mutex → protect shared state")	// Possible to not share? → confinement (best option)	// Protect complex state → sync.Mutex	// Send data between goroutines → channel	// Map with concurrent access → sync.RWMutex + map (or sync.Map)	// Simple counter/flag → atomic	// ─── Decision guide ───	//	// This is the BEST fix: no sharing = no race = no locks.	// }	//     }(i)	//         results[id] = compute(id)  // no sharing	//     go func(id int) {	// for i := range results {	// results := make([][]int, numWorkers)	// // Each worker has its own slice	// Don't share at all! Each goroutine owns its data.	// ─── Option 6: Confinement ───	//	// DON'T use for: general purpose (regular map + mutex is faster)	// Use for: cache-like maps with many readers, few writers	// val, ok := m.Load("key")	// m.Store("key", value)	// var m sync.Map	// ─── Option 5: sync.Map ───	//	// Use for: communicating between goroutines	// }	//     }(item)	//         results <- process(it)	//     go func(it Item) {	// for _, item := range items {	// results := make(chan int, len(items))	// ─── Option 4: Channels ───	//	// Use for: simple counters, flags, pointers	// val := counter.Load()	// counter.Add(1)  // atomic, no lock needed	// var counter atomic.Int64	// ─── Option 3: sync/atomic ───	//	// Use for: read-heavy workloads	// mu.Lock(); cache[key] = val; mu.Unlock()     // exclusive write	// mu.RLock(); val := cache[key]; mu.RUnlock()  // many readers OK	// var mu sync.RWMutex	// ─── Option 2: sync.RWMutex ───	//	// Use for: protecting any shared state	// mu.Unlock()	// counter++	// mu.Lock()	// var mu sync.Mutex	// ─── Option 1: sync.Mutex ───	fmt.Println("--- FIXING RACES ---")func fixingRaces() {// =============================================================================// PART 6: Fixing Races — The Toolkit// =============================================================================}	fmt.Println()	fmt.Println("  Struct fields → use atomic or mutex")	fmt.Println("  Shared append → use channel or mutex")	fmt.Println("  Lazy init → use sync.Once")	fmt.Println("  Check-then-act → use mutex or sync.Map")	// Fix: use atomic.Bool or protect with mutex	// go func() { if s.running { ... } }() // on s.running	// go func() { s.running = true }()   // RACE	// }	//     conns   int	//     running bool	// type Server struct {	// ─── 5. Struct field races ───	//	// Fix: use errgroup.Group from golang.org/x/sync/errgroup	// }	//     }(task)	//         }	//             lastErr = err  // RACE: multiple goroutines write	//         if err := t.Run(); err != nil {	//     go func(t Task) {	// for _, task := range tasks {	// var lastErr error	// ─── 4. Error group without protection ───	//	// Fix: use channel to collect results, or mutex.	// }	//     }(item)	//         results = append(results, process(it))  // RACE	//     go func(it Item) {	// for _, item := range items {	// var results []Result	// ─── 3. Shared slice append ───	//	// }	//     return client	//     once.Do(func() { client = &http.Client{...} })	// func getClient() *http.Client {	// var once sync.Once	// Fix: use sync.Once	// }	//     return client	//     }	//         client = &http.Client{Timeout: 5*time.Second}	//     if client == nil {      // RACE	// func getClient() *http.Client {	// var client *http.Client	// ─── 2. Lazy initialization ───	//	// Fix: use sync.Mutex around the whole block, or sync.Map.	// Two goroutines can both read nil, both compute, both write.	// }	//     cache[key] = compute()  // WRITE	// if cache[key] == nil {    // READ	// ─── 1. Check-then-act ───	fmt.Println("--- COMMON RACE PATTERNS ---")func commonRacePatterns() {// =============================================================================// PART 5: Common Race Patterns// =============================================================================}	fmt.Println()	fmt.Println("  Exit code 66 = race detected")	fmt.Println("  GORACE=\"halt_on_error=1\" → fail fast")	fmt.Println("  go test -race -count=1 ./... in CI pipeline")	// 4. Use -short flag to skip slow tests in race runs	// 3. Run race tests nightly instead of every push	// 2. Only run race tests on changed packages	// 1. Run race tests on a separate, parallel CI job	// Race detection is slow. Options:	// ─── Cost mitigation in CI ───	//	// GORACE="halt_on_error=1 atexit_sleep_ms=0" go test -race -count=1 -timeout=5m ./...	// ─── Recommended CI setup ───	//	// history_size=N   Per-goroutine history (default: 1, increase for complex races)	// atexit_sleep_ms=0  Don't sleep at exit (faster test runs)	// halt_on_error=1  Exit immediately on first race (default: 0)	// log_path=path    Write race reports to file (default: stderr)	// GORACE options:	//	// GORACE="log_path=race.log halt_on_error=1"	// ─── Environment variable ───	//	// CI systems will catch this as a failure.	//   (plus the normal exit code from test failures)	// Race detector returns exit code 66 when a race is found	// ─── Exit code ───	//	// -race: enable race detection	// -count=1: bypass test cache (race results aren't cached)	//	// go test -race -count=1 ./...	// ─── Add to CI pipeline ───	fmt.Println("--- RACE DETECTOR IN CI ---")func raceInCI() {// =============================================================================// PART 4: Race Detector in CI// =============================================================================}	fmt.Println()	fmt.Println("  same slice append → RACE")	fmt.Println("  different slice indices → SAFE (pre-allocated)")	fmt.Println("  concurrent map writes → RACE (and panic)")	fmt.Println("  counter++ in goroutine → RACE")	// // Go 1.22+: loop variable is per-iteration (no race)	// // Fix: go func(n int) { fmt.Println(n) }(i)	// }	//     }()	//         fmt.Println(i)  // RACE: reads i while loop increments it	//     go func() {	// for i := 0; i < 10; i++ {	// ─── Example 4: Closure variable race ───	//	// // But appending to same slice → RACE (modifies slice header).	// // Writing to different indices of PRE-ALLOCATED slice is safe.	// }	//     }(i)	//         results[idx] = compute(idx)  // SAFE if different indices!	//     go func(idx int) {	// for i := 0; i < 10; i++ {	// results := make([]int, 10)	// ─── Example 3: Slice race ───	//	// // Go 1.6+ will panic: "fatal error: concurrent map writes"	// // Maps are NOT safe for concurrent access in Go!	// go func() { m["b"] = 2 }()  // RACE (concurrent map write)	// go func() { m["a"] = 1 }()  // RACE	// m := make(map[string]int)	// ─── Example 2: Map race ───	//	// // counter might be 980, 995, 1000... unpredictable	// wg.Wait()	// }	//     }()	//         counter++  // RACE: unsynchronized write	//         defer wg.Done()	//     go func() {	//     wg.Add(1)	// for i := 0; i < 1000; i++ {	// var wg sync.WaitGroup	// var counter int	// ─── Example 1: Simple counter race ───	fmt.Println("--- RACE EXAMPLES ---")func raceExamples() {// =============================================================================// PART 3: Race Examples// =============================================================================}	fmt.Println()	fmt.Println("  Only detects races in executed code paths")	fmt.Println("  ZERO false positives: if reported, it's real")	fmt.Println("  Based on ThreadSanitizer (happens-before algorithm)")	// that actually happen during execution.	// But no false negatives guarantee: it can only catch races	// If it reports a race, it IS a race. Period.	// The race detector has ZERO false positives.	//	// ✗ Atomic operation ordering issues	// ✗ Races in cgo/C code	// ✗ Races in code that doesn't execute (need good test coverage!)	// ✗ Deadlocks (use go vet -copylocks or manual inspection)	// ─── What it does NOT detect ───	//	// ✓ Races on global variables	// ✓ Races on slice elements	// ✓ Races on struct fields	// ✓ Races on map access	// ✓ Concurrent write + write to same variable	// ✓ Concurrent read + write to same variable	// ─── What it detects ───	//	// relationship → DATA RACE detected.	// If two accesses to the same memory have NO happens-before	// The race detector tracks these relationships at runtime.	//	// - close(ch) happens-before receive of zero value	// - WaitGroup.Add happens-before the go statement	// - sync.Once.Do(f) happens-before any Do returns	// - Mutex unlock happens-before the next lock	// - A send on a channel happens-before the receive completes	// Go's memory model defines "happens-before" relationships:	// ─── Happens-before ───	//	// Uses happens-before algorithm.	// Built on ThreadSanitizer (TSan) from Google.	fmt.Println("--- HOW IT WORKS ---")func howItWorks() {// =============================================================================// PART 2: How the Race Detector Works// =============================================================================}	fmt.Println()	fmt.Println("  Shows exact lines, goroutines, and stacks")	fmt.Println("  ~10x CPU overhead — use in dev/CI, not production")	fmt.Println("  go test -race ./... → detect data races")	// 4. WHEN: which access was the read and which was the write	// 3. WHERE: exact file:line for both accesses	// 2. WHO: which goroutines (with creation stack traces)	// 1. WHAT: which memory address was accessed	// It tells you:	//	// ==================	//       main.go:7 +0x5c	//   main.main()	// Goroutine 6 (finished) created at:	//	//       main.go:8 +0x7c	//   main.main()	// Goroutine 7 (running) created at:	//	//       main.go:20 +0x2c	//   main.read()	// Previous read at 0x00c0000b4010 by goroutine 6:	//	//       main.go:15 +0x38	//   main.increment()	// Write at 0x00c0000b4010 by goroutine 7:	// WARNING: DATA RACE	// ==================	// When a race is detected:	// ─── Output format ───	//	// NOT for production. Use in development and CI.	//	// Binary: ~2x larger	// Memory: ~5-10x more	// CPU:    ~10x slower	// ─── Cost ───	//	// go build -race -o myapp       # build with race detection	// go test -race ./...           # test with race detection	// go run -race main.go          # run with race detection	// ─── Enable the race detector ───	//	// memory corruption — all INTERMITTENTLY (hard to reproduce).	// Data races cause: corrupted data, crashes, wrong results,	//	// AND there's no synchronization between them.	// AND at least one access is a WRITE,	// Two goroutines access the same variable concurrently,	// ─── What is a data race? ───	fmt.Println("--- RACE DETECTOR BASICS ---")func raceDetectorBasics() {// =============================================================================// PART 1: Race Detector Basics// =============================================================================}	fixingRaces()	commonRacePatterns()	raceInCI()	raceExamples()	howItWorks()	raceDetectorBasics()	fmt.Println()	fmt.Println("=== RACE DETECTOR ===")func main() {import "fmt"package main// =============================================================================// RUN: go run 06_race_detector.go//// to shared memory. If there's a data race, it will find it.// It instruments your code to detect concurrent unsynchronized access// The race detector is Go's most important concurrency debugging tool.//// =============================================================================// GO TOOLCHAIN 6: RACE DETECTOR — Find Data Races Before They Find You// =============================================================================