//go:build ignore

// =============================================================================
// GO TOOLCHAIN 9: go generate & CODE GENERATION
// =============================================================================
//
// go generate runs commands embedded in your Go source files.
// It's the standard way to automate code generation in Go:
// - Generate mocks for testing
// - Generate protocol buffers
// - Generate enum string methods
// - Embed resources
// - Generate SQL boilerplate
//
// RUN: go run 09_go_generate.go
// =============================================================================

package main

import "fmt"

func main() {
	fmt.Println("=== go generate & CODE GENERATION ===")
	fmt.Println()
	generateBasics()
	commonGenerators()
	stringerTool()
	mockGeneration()
	protoGeneration()
	embedDirective()
	writeYourOwnGenerator()
}

// =============================================================================
// PART 1: go generate Basics
// =============================================================================
func generateBasics() {
	fmt.Println("--- go generate BASICS ---")
	// ─── What is go generate? ───
	// A command that scans Go source files for //go:generate directives
	// and runs the specified commands.
	//
	// It does NOT run during build/test. You run it manually.
	// The generated code is committed to version control.
	//
	// ─── Syntax ───
	// //go:generate command arg1 arg2
	//
	// Must be at the start of the line (after //).
	// No space between // and go:generate.
	//
	// ─── Running ───
	// go generate              # process current package
	// go generate ./...        # process all packages
	// go generate -v ./...     # verbose (show commands)
	// go generate -n ./...     # dry run (show commands without running)
	// go generate -run "stringer" ./...  # only run matching generators
	//
	// ─── How it works ───
	// 1. Scans .go files for //go:generate comments
	// 2. Runs each command in order
	// 3. Commands generate .go files
	// 4. You commit the generated files
	//
	// ─── Special variables ───
	// //go:generate echo $GOFILE    # current filename
	// //go:generate echo $GOPACKAGE # current package name
	// //go:generate echo $GOLINE    # line number of directive
	// //go:generate echo $GOARCH    # target architecture
	// //go:generate echo $GOOS      # target OS
	// //go:generate echo $DOLLAR    # literal $ character
	//
	// ─── Convention ───
	// Generated files should start with:
	// // Code generated by <tool>; DO NOT EDIT.
	// This comment tells editors and tools to skip the file.
	fmt.Println("  //go:generate command args → embed generate commands")
	fmt.Println("  go generate ./... → run all generators")
	fmt.Println("  Generated files → commit to VCS")
	fmt.Println("  Convention: // Code generated by ...; DO NOT EDIT.")
	fmt.Println()
}

// =============================================================================
// PART 2: Common Generators
// =============================================================================
func commonGenerators() {
	fmt.Println("--- COMMON GENERATORS ---")
	// ─── stringer (stdlib) ───
	// Generates String() method for integer enum types
	// go install golang.org/x/tools/cmd/stringer@latest
	// //go:generate stringer -type=Color
	//
	// ─── mockgen (uber) ───
	// Generates mock implementations of interfaces
	// go install go.uber.org/mock/mockgen@latest
	// //go:generate mockgen -source=service.go -destination=mock_service.go
	//
	// ─── protoc-gen-go (protobuf) ───
	// Generates Go code from .proto files
	// //go:generate protoc --go_out=. --go-grpc_out=. service.proto
	//
	// ─── sqlc ───
	// Generates type-safe Go code from SQL queries
	// //go:generate sqlc generate
	//
	// ─── wire (Google) ───
	// Compile-time dependency injection
	// go install github.com/google/wire/cmd/wire@latest
	// //go:generate wire ./...
	//
	// ─── ent (Facebook) ───
	// ORM code generation
	// //go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema
	//
	// ─── oapi-codegen ───
	// Generate Go server/client from OpenAPI spec
	// //go:generate oapi-codegen -package api spec.yaml > api.gen.go
	//
	// ─── enumer ───
	// Like stringer but with more features (JSON, SQL, validation)
	// //go:generate enumer -type=Status -json -sql
	fmt.Println("  stringer → String() for enums")
	fmt.Println("  mockgen → mock interfaces for tests")
	fmt.Println("  protoc → Protocol Buffers")
	fmt.Println("  sqlc → type-safe SQL")
	fmt.Println("  wire → dependency injection")
	fmt.Println()
}

// =============================================================================
// PART 3: stringer Tool — Deep Dive
// =============================================================================
func stringerTool() {
	fmt.Println("--- stringer ---")
	// ─── Problem ───
	// type Day int
	// const (
	//     Sunday Day = iota
	//     Monday
	//     Tuesday
	// )
	// fmt.Println(Sunday) // prints: 0 (not useful!)
	//
	// ─── Solution: generate String() method ───
	// //go:generate stringer -type=Day
	//
	// This creates day_string.go with:
	// func (d Day) String() string {
	//     // returns "Sunday", "Monday", etc.
	// }
	// Now: fmt.Println(Sunday) // prints: Sunday
	//
	// ─── Flags ───
	// stringer -type=Day              # basic generation
	// stringer -type=Day,Color        # multiple types
	// stringer -type=Day -output=day_string.go  # custom filename
	// stringer -type=Day -linecomment # use line comments as names
	//
	// ─── Line comments ───
	// const (
	//     Sunday Day = iota // Sun
	//     Monday            // Mon
	//     Tuesday           // Tue
	// )
	// //go:generate stringer -type=Day -linecomment
	// Now: Sunday.String() == "Sun"
	//
	// ─── Full example ───
	// // file: status.go
	// package order
	//
	// //go:generate stringer -type=Status
	//
	// type Status int
	// const (
	//     Pending  Status = iota  // 0
	//     Active                  // 1
	//     Complete                // 2
	//     Cancelled               // 3
	// )
	//
	// Run: go generate ./...
	// Creates: status_string.go (auto-generated, don't edit)
	fmt.Println("  stringer -type=Enum → generate String() method")
	fmt.Println("  -linecomment → use comments as display names")
	fmt.Println("  Prints enum names instead of numbers")
	fmt.Println()
}

// =============================================================================
// PART 4: Mock Generation
// =============================================================================
func mockGeneration() {
	fmt.Println("--- MOCK GENERATION ---")
	// ─── Why mocks? ───
	// You have an interface (e.g., UserStore).
	// In tests, you don't want a real database.
	// Generate a mock that implements the interface.
	//
	// ─── mockgen (uber, current standard) ───
	// go install go.uber.org/mock/mockgen@latest
	//
	// Source mode (from source file):
	// //go:generate mockgen -source=store.go -destination=mock_store.go -package=mocks
	//
	// Reflect mode (from interface name):
	// //go:generate mockgen -destination=mock_store.go -package=mocks mymodule/store UserStore
	//
	// ─── Using the mock in tests ───
	// func TestGetUser(t *testing.T) {
	//     ctrl := gomock.NewController(t)
	//     mockStore := mocks.NewMockUserStore(ctrl)
	//
	//     mockStore.EXPECT().
	//         GetByID(gomock.Any(), int64(42)).
	//         Return(&User{Name: "alice"}, nil)
	//
	//     svc := NewUserService(mockStore)
	//     user, err := svc.GetUser(ctx, 42)
	//     assert.NoError(t, err)
	//     assert.Equal(t, "alice", user.Name)
	// }
	//
	// ─── Alternative: counterfeiter ───
	// go install github.com/maxbrunsfeld/counterfeiter/v6@latest
	// //go:generate counterfeiter -o fakes/fake_store.go . UserStore
	//
	// ─── Alternative: moq ───
	// go install github.com/matryer/moq@latest
	// //go:generate moq -out mock_store.go . UserStore
	// Generates simple struct-based mocks (no framework).
	fmt.Println("  mockgen -source=x.go → generate interface mocks")
	fmt.Println("  EXPECT().Method().Return() → set expectations")
	fmt.Println("  Alternatives: counterfeiter, moq")
	fmt.Println()
}

// =============================================================================
// PART 5: Protocol Buffer Generation
// =============================================================================
func protoGeneration() {
	fmt.Println("--- PROTOBUF GENERATION ---")
	// ─── Install tools ───
	// # protoc compiler (language-independent)
	// apt install protobuf-compiler  # or brew install protobuf
	//
	// # Go plugins
	// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
	//
	// ─── Proto file ───
	// // proto/user.proto
	// syntax = "proto3";
	// package user;
	// option go_package = "myapp/gen/userpb";
	//
	// service UserService {
	//     rpc GetUser(GetUserRequest) returns (GetUserResponse);
	// }
	// message GetUserRequest {
	//     int64 id = 1;
	// }
	// message GetUserResponse {
	//     string name = 1;
	//     string email = 2;
	// }
	//
	// ─── Generate directive ───
	// //go:generate protoc --go_out=. --go_opt=paths=source_relative \
	// //   --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	// //   proto/user.proto
	//
	// Generates:
	// - user.pb.go (message types)
	// - user_grpc.pb.go (gRPC client/server stubs)
	//
	// ─── buf: modern protobuf toolchain ───
	// Better than raw protoc. Handles dependencies, linting, formatting.
	// # Install: https://buf.build/docs/installation
	// buf generate    # replaces protoc commands
	// buf lint        # lint proto files
	// buf breaking    # detect breaking changes
	fmt.Println("  protoc --go_out → generate Go from .proto")
	fmt.Println("  protoc-gen-go-grpc → generate gRPC stubs")
	fmt.Println("  buf → modern protobuf toolchain (recommended)")
	fmt.Println()
}

// =============================================================================
// PART 6: //go:embed — Embed Files at Compile Time
// =============================================================================
func embedDirective() {
	fmt.Println("--- go:embed ---")
	// ─── Embed files into your Go binary (Go 1.16+) ───
	// import "embed"
	//
	// //go:embed config.json
	// var configData []byte
	//
	// //go:embed template.html
	// var templateStr string
	//
	// //go:embed static/*
	// var staticFiles embed.FS
	//
	// ─── Rules ───
	// - Must be package-level variable
	// - Variable type: string, []byte, or embed.FS
	// - Paths are relative to the source file
	// - Directories embedded recursively
	// - Files starting with . or _ excluded by default
	//   Use //go:embed all:static to include them
	//
	// ─── embed.FS usage ───
	// //go:embed templates/*
	// var templates embed.FS
	//
	// // Use with http.FileServer:
	// http.Handle("/static/", http.FileServer(http.FS(staticFiles)))
	//
	// // Use with template.ParseFS:
	// tmpl, _ := template.ParseFS(templates, "templates/*.html")
	//
	// // Read specific file:
	// data, _ := templates.ReadFile("templates/index.html")
	//
	// ─── Use cases ───
	// - Embed SQL migration files
	// - Embed HTML/CSS/JS for web servers (single binary deploy!)
	// - Embed config defaults
	// - Embed version info
	// - Embed CA certificates
	//
	// ─── NOT go generate ───
	// embed is a compiler directive, not go generate.
	// It runs at build time automatically.
	// No //go:generate needed.
	fmt.Println("  //go:embed file.txt → embed file in binary")
	fmt.Println("  embed.FS → embed whole directories")
	fmt.Println("  Single binary with all static files!")
	fmt.Println("  Not go:generate — runs at build time")
	fmt.Println()
}

// =============================================================================
// PART 7: Writing Your Own Generator
// =============================================================================
func writeYourOwnGenerator() {
	fmt.Println("--- CUSTOM GENERATOR ---")
	// ─── When to write your own ───
	// - Generate boilerplate from a schema
	// - Generate type-safe wrappers
	// - Generate validation code
	// - Generate routing tables from annotations
	//
	// ─── Approach 1: text/template ───
	// Load a Go template, feed it data, write output.
	//
	// // gen/main.go
	// func main() {
	//     tmpl := template.Must(template.ParseFiles("template.go.tmpl"))
	//     f, _ := os.Create("generated.go")
	//     tmpl.Execute(f, data)
	// }
	// //go:generate go run ./gen/
	//
	// ─── Approach 2: go/ast + go/parser ───
	// Parse Go source files, inspect types, generate code.
	// This is how stringer works internally.
	//
	// fset := token.NewFileSet()
	// pkgs, _ := parser.ParseDir(fset, ".", nil, 0)
	// for _, pkg := range pkgs {
	//     for _, file := range pkg.Files {
	//         ast.Inspect(file, func(n ast.Node) bool {
	//             // find type declarations, generate code
	//             return true
	//         })
	//     }
	// }
	//
	// ─── Approach 3: go/packages (recommended) ───
	// Higher-level API that handles modules, build tags, etc.
	// cfg := &packages.Config{Mode: packages.NeedTypes | packages.NeedSyntax}
	// pkgs, _ := packages.Load(cfg, "./...")
	// // inspect types and generate code
	//
	// ─── Generated file header ───
	// Always start generated files with:
	// // Code generated by mygentools; DO NOT EDIT.
	//
	// And always format the output:
	// formatted, _ := format.Source(generated)
	// os.WriteFile("output.go", formatted, 0644)
	fmt.Println("  text/template → simple code generation")
	fmt.Println("  go/ast + go/parser → parse Go source")
	fmt.Println("  go/packages → recommended for type info")
	fmt.Println("  Always: format.Source() the output")
	fmt.Println()
}
