package stdlibmastery























































































































































































































































































































































































































































































































































































































































































































































































}	fmt.Println()	_ = errors.New("placeholder") // use errors package	// For high-throughput: measure with benchmarks + pprof	//	//   []int{1,2,3}       → 7 bytes "[1,2,3]"	//   struct with 5 fields → ~200-500 bytes typically	//   empty struct {}     → 2 bytes "{}"	// json.Marshal allocates at least:	// ─── COMMON MARSHAL SIZES ───	// Use json.Number (via Decoder.UseNumber()) when you must use interface{}.	// ALWAYS unmarshal into typed structs when possible.	//	//   JSON null    → nil	//   JSON object  → map[string]interface{}	//   JSON array   → []interface{}	//   JSON string  → string	//   JSON number  → float64 (precision loss for int64!)	//   JSON boolean → bool	// json.Unmarshal into interface{} uses these Go types:	// ─── UNMARSHAL TO SPECIFIC TYPE vs interface{} ───	fmt.Println("  Tip 7: Use \",string\" tag for int64 IDs consumed by JavaScript")	// The ",string" tag prevents silent precision loss	// Go int64 max = 2^63 - 1 = 9223372036854775807	// JavaScript Number.MAX_SAFE_INTEGER = 2^53 - 1 = 9007199254740991	// TIP 7: Use ",string" tag for int64 IDs sent to JavaScript	fmt.Println("  Tip 6: Reuse json.Encoder/Decoder for multiple values")	// TIP 6: Reuse Encoder/Decoder when processing many values	fmt.Println("  Tip 5: For hot paths: json-iterator, sonic, or go-json")	// - encoding/json/v2 (proposed, may land in Go 1.24+)	// - github.com/goccy/go-json (2-3x faster, better compatibility)	// - github.com/bytedance/sonic (SIMD-based, 5-10x faster)	// - github.com/json-iterator/go (drop-in, 2-3x faster)	// TIP 5: For ultra-high performance, consider:	fmt.Printf("  Tip 4: Custom marshal: %s\n", data)	data, _ := json.Marshal(p) // uses our custom MarshalJSON	p := Point{X: 1.5, Y: 2.7}	// TIP 4: Custom MarshalJSON avoids reflection (shown above)	fmt.Println("  Tip 3: Pre-allocate slices before Unmarshal")	// FAST: Initialize with expected capacity before unmarshal	// SLOW: Items []Item (nil, grows with append during unmarshal)	// TIP 3: Pre-allocate slices in your struct	fmt.Printf("  Tip 2: json.Valid: good=%v, bad=%v\n", good, bad)	bad := json.Valid([]byte(`{invalid json`))	good := json.Valid([]byte(`{"valid": true}`))	// TIP 2: Use json.Valid to check before expensive operations	fmt.Println("  Tip 1: json.Decoder for HTTP bodies (no intermediate alloc)")	// BAD:  body, _ := io.ReadAll(r.Body); json.Unmarshal(body, &v)	// GOOD: json.NewDecoder(r.Body).Decode(&v)	// TIP 1: Use json.Decoder for HTTP bodies (no intermediate []byte)	fmt.Println("--- PERFORMANCE TIPS ---")func performanceTips() {}	return json.Valid(data)func isValidJSON(data []byte) bool {// ── Validate JSON without full parsing ──}	return buf.Bytes(), nil	buf.WriteByte('}')	fmt.Fprintf(&buf, `"x":%.6f,"y":%.6f`, p.X, p.Y)	buf.WriteByte('{')	var buf bytes.Buffer	// Hand-written: ~3x faster than reflection-based marshalfunc (p Point) MarshalJSON() ([]byte, error) {}	X, Y float64type Point struct {// Avoids reflection overhead entirely// ── Implement json.Marshaler for hot-path types ──// =============================================================================// PART 8: Performance Tips// =============================================================================}	fmt.Println()	fmt.Printf("  Type mismatch: n=%d, err=%v\n", x.N, err) // err is non-nil, but many devs ignore it	err := json.Unmarshal([]byte(`{"n": "abc"}`), &x)	// String "abc" for int field: silently keeps zero value!	}		N int `json:"n"`	var x struct {	// ─── PITFALL 6: Errors are silently ignored ───	fmt.Printf("  Interface unmarshal type: %T\n", c2.Value) // map[string]interface{}	// c2.Value is map[string]interface{}, NOT map[string]string!	json.Unmarshal(d7, &c2)	var c2 Container	fmt.Printf("  Interface marshal: %s\n", d7) // works fine	d7, _ := json.Marshal(c)	c := Container{Value: map[string]string{"key": "val"}}	}		Value interface{} `json:"value"`	type Container struct {	// ─── PITFALL 5: Interface fields marshal fine but unmarshal to map ───	fmt.Printf("  Field shadow: %s\n", d6) // "name": "extended" (outer wins)	d6, _ := json.Marshal(ext)	ext := Extended{Base: Base{ID: 1, Name: "base"}, Name: "extended"}	}		Name string `json:"name"` // shadows Base.Name!		Base	type Extended struct {	}		Name string `json:"name"`		ID   int    `json:"id"`	type Base struct {	// ─── PITFALL 4: Embedded struct field conflicts ───	fmt.Printf("  Unexported field: %s\n", d5) // only "public"	d5, _ := json.Marshal(internal{Public: "visible", private: "invisible"})	}		private string `json:"private"` // NOT marshaled — lowercase = unexported		Public  string `json:"public"`	type internal struct {	// ─── PITFALL 3: Unexported fields are invisible ───	fmt.Printf("  empty map: %s\n", d4) // {"settings":{}}	fmt.Printf("  nil map:   %s\n", d3) // {"settings":null}	d4, _ := json.Marshal(Config{Settings: map[string]string{}})	d3, _ := json.Marshal(Config{Settings: nil})	}		Settings map[string]string `json:"settings"`	type Config struct {	// Same issue: nil map → "null", empty map → "{}"	// ─── PITFALL 2: nil map vs empty map ───	// → APIs should usually return [] not null. Initialize slices!	fmt.Printf("  empty slice: %s\n", d2) // {"items":[]}	fmt.Printf("  nil slice:   %s\n", d1) // {"items":null}	d2, _ := json.Marshal(emptySlice)	d1, _ := json.Marshal(nilSlice)	emptySlice := Response{Items: []string{}}	nilSlice := Response{Items: nil}	}		Items []string `json:"items"`	type Response struct {	// nil slice marshals to "null", empty slice marshals to "[]"	// ─── PITFALL 1: nil slice vs empty slice ───	fmt.Println("--- COMMON PITFALLS ---")func commonPitfalls() {// =============================================================================// PART 7: Common Pitfalls// =============================================================================}	fmt.Println()	fmt.Printf("  Notification: channel=%q, payload=%+v\n", notif.Channel, notif.Payload)	json.Unmarshal([]byte(notifJSON), &notif)	var notif Notification	notifJSON := `{"channel":"email","payload":{"to":"v@test.com","subject":"Hello"}}`	// Notification pattern	}		fmt.Printf("  Event %q → %+v\n", evt.Type, parsed)		parsed, _ := evt.ParseData()		json.Unmarshal([]byte(raw), &evt)		var evt Event	for _, raw := range events {	}		`{"type":"order.placed","data":{"order_id":"ORD-123","total":99.99}}`,		`{"type":"user.created","data":{"user_id":1,"name":"Vikram"}}`,	events := []string{	// Event routing pattern	fmt.Println("--- POLYMORPHIC JSON ---")func polymorphicJSON() {}	return nil	}		n.Payload = raw.Payload		// Keep raw JSON for unknown channels	default:		n.Payload = sms		}			return err		if err := json.Unmarshal(raw.Payload, &sms); err != nil {		}			Message string `json:"message"`			Phone   string `json:"phone"`		var sms struct {	case "sms":		n.Payload = email		}			return err		if err := json.Unmarshal(raw.Payload, &email); err != nil {		}			Subject string `json:"subject"`			To      string `json:"to"`		var email struct {	case "email":	switch raw.Channel {	// Step 2: decode payload based on channel	n.Channel = raw.Channel	}		return err	if err := json.Unmarshal(data, &raw); err != nil {	}		Payload json.RawMessage `json:"payload"`		Channel string          `json:"channel"`	var raw struct {	// Step 1: parse known fields + raw payloadfunc (n *Notification) UnmarshalJSON(data []byte) error {}	Payload any    // populated based on Channel	Channel string `json:"channel"`type Notification struct {// ── UnmarshalJSON on the container for seamless API ──}	}		return nil, fmt.Errorf("unknown event type: %q", e.Type)	default:		return &d, json.Unmarshal(e.Data, &d)		var d OrderPlaced	case "order.placed":		return &d, json.Unmarshal(e.Data, &d)		var d UserCreated	case "user.created":	switch e.Type {func (e *Event) ParseData() (interface{}, error) {}	Total   float64 `json:"total"`	OrderID string  `json:"order_id"`type OrderPlaced struct {}	Name   string `json:"name"`	UserID int    `json:"user_id"`type UserCreated struct {}	Data json.RawMessage `json:"data"`	Type string          `json:"type"`type Event struct {// This is extremely common in event-driven systems and webhooks.// API returns different shapes based on a discriminator field.// ── The "type" + "data" pattern ──// =============================================================================// PART 6: Polymorphic JSON — Different shapes based on a type field// =============================================================================}	fmt.Println()	fmt.Printf("  json.Number string: %q, float: %f\n", fv.Value.String(), asFloat)	asFloat, _ := fv.Value.Float64()	// Can read as int or float depending on what you need	json.Unmarshal([]byte(`{"value": 3.14159}`), &fv)	var fv FlexValue	}		Value json.Number `json:"value"`	type FlexValue struct {	// and for preserving the original string representation	// json.Number is also useful for distinguishing "missing" from "0"	fmt.Printf("  Typed struct (BEST): id = %d\n", rec.ID)	json.Unmarshal([]byte(bigJSON), &rec)	var rec Record	}		ID int64 `json:"id"`	type Record struct {	// Or better: unmarshal into a typed struct	fmt.Printf("  json.Number (RIGHT): id = %d (exact!)\n", id)	id, _ := numStr.Int64()	numStr := right["id"].(json.Number)	dec.Decode(&right)	var right map[string]interface{}	dec.UseNumber() // tells decoder to use json.Number instead of float64	dec := json.NewDecoder(strings.NewReader(bigJSON))	// RIGHT: use json.Number via Decoder	fmt.Printf("  float64 (WRONG): id = %.0f (precision lost!)\n", wrong["id"].(float64))	// id is float64, precision lost!	json.Unmarshal([]byte(bigJSON), &wrong)	var wrong map[string]interface{}	bigJSON := `{"id": 9223372036854775807}`	// WRONG: default unmarshaling loses precision	// it becomes 9223372036854776000. Silent data corruption!	// If your ID is 9223372036854775807 and it goes through float64,	//	// float64 max: 9007199254740992    (16 digits exact)	// int64 max:   9223372036854775807 (19 digits)	//	// float64 can only represent integers exactly up to 2^53.	// Go's json.Unmarshal to interface{} also defaults to float64.	// JSON numbers have no size limit. JavaScript uses float64 (IEEE 754).	// THE PROBLEM:	fmt.Println("--- JSON NUMBER PRECISION ---")func jsonNumberPrecision() {// =============================================================================// PART 5: json.Number — Precision-Sensitive Numbers// =============================================================================}	fmt.Println()	// }	//     json.NewEncoder(w).Encode(response)	//     w.Header().Set("Content-Type", "application/json")	//     // Encode directly to response writer	//	//     }	//         return	//         http.Error(w, "unexpected data after JSON", http.StatusBadRequest)	//     if dec.More() {	//     // Reject body with extra data after the JSON value	//     }	//         return	//         http.Error(w, err.Error(), http.StatusBadRequest)	//     if err := dec.Decode(&req); err != nil {	//     dec.DisallowUnknownFields()	//     dec := json.NewDecoder(r.Body)	//     // Decode directly from body — don't io.ReadAll first!	//     var req CreateUserRequest	// func handler(w http.ResponseWriter, r *http.Request) {	// ─── Streaming HTTP pattern (commented) ───	fmt.Printf("  NDJSON output: %q\n", ndjsonBuf.String())	ndjsonEnc.Encode(LogEvent{Event: "stop", TS: 2})	ndjsonEnc.Encode(LogEvent{Event: "start", TS: 1})	ndjsonEnc := json.NewEncoder(&ndjsonBuf)	var ndjsonBuf bytes.Buffer	// ─── Encoder: write multiple values (NDJSON output) ───	fmt.Printf("  Encoded to buffer:\n%s", buf.String())	enc.Encode(Item{Name: "Go Book", Price: 49})	enc.SetEscapeHTML(false)      // don't escape <, >, & (for non-HTML output)	enc.SetIndent("", "  ")      // pretty print	enc := json.NewEncoder(&buf)	var buf bytes.Buffer	// ─── Encoder: write to a Writer ───	fmt.Println()	}		fmt.Printf("[%s@%d] ", evt.Event, evt.TS)		}			break			fmt.Printf("error: %v", err)		} else if err != nil {			break		if err := streamDec.Decode(&evt); err == io.EOF {		var evt LogEvent	for {	fmt.Print("  NDJSON stream: ")	streamDec := json.NewDecoder(strings.NewReader(ndjson))	}		TS    int    `json:"ts"`		Event string `json:"event"`	type LogEvent struct {`{"event":"submit","ts":3}{"event":"scroll","ts":2}	ndjson := `{"event":"click","ts":1}	// Each line is a separate JSON value — common in log processing	// ─── Decoder: NDJSON (newline-delimited JSON) streaming ───	fmt.Printf("  Strict decode error: %v\n", err) // unknown field "color"	err := strictDec.Decode(&item2)	var item2 Item	strictDec.DisallowUnknownFields()	strictDec := json.NewDecoder(strings.NewReader(strictJSON))	strictJSON := `{"name":"phone","price":599,"color":"red"}`	// ─── Decoder: DisallowUnknownFields (strict parsing) ───	fmt.Printf("  Decoded from stream: %+v\n", item)	}		fmt.Printf("  decode error: %v\n", err)	if err := dec.Decode(&item); err != nil {	var item Item	dec := json.NewDecoder(strings.NewReader(jsonStream))	jsonStream := `{"name":"laptop","price":999}`	}		Price int    `json:"price"`		Name  string `json:"name"`	type Item struct {	// ─── Decoder: parse from a Reader ───	// - Need the []byte result (e.g., to store in a cache)	// - Working with small, in-memory data	// USE json.Marshal WHEN:	//	// - You want to fail fast on unknown fields (DisallowUnknownFields)	// - Reading multiple JSON values from a stream (NDJSON)	// - Processing large JSON files/streams	// - Reading from HTTP response body (io.Reader)	// USE json.Decoder WHEN:	//	// json.Encoder/Decoder: work with io.Writer/io.Reader (stream-based)	// json.Marshal/Unmarshal: work with []byte (entire document in memory)	fmt.Println("--- STREAMING JSON ---")func streamingJSON() {// =============================================================================// PART 4: Streaming JSON — json.Decoder and json.Encoder// =============================================================================}	fmt.Println()	fmt.Printf("  Dynamic fields: name=%q, features=%s\n", name, fields["features"])	// Pass through unknown fields without parsing	json.Unmarshal(fields["name"], &name)	var name string	// Extract known fields	json.Unmarshal([]byte(configJSON), &fields)	var fields map[string]json.RawMessage	// Parse everything into a map with RawMessage values	}`		"max_retries": 3		"features": {"dark_mode": true, "beta": false},		"version": "1.0",		"name": "myapp",	configJSON := `{	// Parse a map of known + unknown fields	// ─── USE CASE 3: Unknown/dynamic fields ───	// Without RawMessage, the nested JSON would be double-encoded as a string	fmt.Printf("  Pre-computed: %s\n", output)	output, _ := json.Marshal(cr)	cr := CachedResponse{Status: "ok", Body: cachedJSON}	cachedJSON := json.RawMessage(`{"items":[1,2,3],"total":3}`)	}		Body   json.RawMessage `json:"body"` // already JSON, don't re-encode		Status string          `json:"status"`	type CachedResponse struct {	// embed it without double-encoding.	// When you have JSON that's already marshaled (e.g., from a cache or DB),	// ─── USE CASE 2: Pre-computed JSON (embed pre-marshaled data) ───	}		fmt.Printf("  Decoded user: %+v\n", user)		json.Unmarshal(resp.Data, &user)		var user UserData	if resp.Type == "user" {	}		Email string `json:"email"`		Name  string `json:"name"`		ID    int    `json:"id"`	type UserData struct {	// Now parse Data based on Type	fmt.Printf("  Partial parse: type=%q, raw data=%s\n", resp.Type, resp.Data)	json.Unmarshal([]byte(raw), &resp)	var resp APIResponse	raw := `{"type":"user","data":{"id":1,"name":"Vikram","email":"v@test.com"}}`	}		Data json.RawMessage `json:"data"` // NOT parsed yet		Type string          `json:"type"`	type APIResponse struct {	// ─── USE CASE 1: Partial parsing (parse envelope, delay body) ───	// 4. Pre-compute JSON to avoid repeated marshaling	// 3. Pass through JSON without parsing (proxy/forward)	// 2. Delay parsing until you know the type	// 1. Parse only part of a large JSON document	// USE CASES:	//	// It implements json.Marshaler and json.Unmarshaler.	// json.RawMessage is just []byte that isn't parsed yet.	fmt.Println("--- RAW MESSAGE PATTERNS ---")func rawMessagePatterns() {// =============================================================================// PART 3: json.RawMessage — Partial/Lazy/Polymorphic Parsing// =============================================================================}	fmt.Println()	// 5. ALWAYS handle "null" in UnmarshalJSON	// 4. If used as value (T), only MarshalJSON works	// 3. If the type is used as a pointer (*T), both work fine	// 2. UnmarshalJSON is called on POINTER receiver: func (t *T) UnmarshalJSON()	// 1. MarshalJSON is called on VALUE receiver: func (t T) MarshalJSON()	// ─── MarshalJSON rules to remember ───	fmt.Printf("  Enum unmarshal: %s → Status=%d\n", j2.Name, j2.Status)	json.Unmarshal([]byte(`{"name":"deploy","status":"paused"}`), &j2)	var j2 Job	fmt.Printf("  Enum marshal: %s\n", jData) // {"name":"build","status":"active"}	jData, _ := json.Marshal(j)	j := Job{Name: "build", Status: StatusActive}	}		Status Status `json:"status"`		Name   string `json:"name"`	type Job struct {	// Status enum in action	fmt.Printf("  DateOnly unmarshal: %s on %s\n", e2.Name, e2.Date.Format("2006-01-02"))	json.Unmarshal([]byte(`{"name":"Workshop","date":"2025-03-20"}`), &e2)	var e2 Event	fmt.Printf("  DateOnly marshal: %s\n", data)	data, _ := json.Marshal(e)	}		Date: DateOnly{time.Date(2024, 11, 15, 0, 0, 0, 0, time.UTC)},		Name: "Go Conference",	e := Event{	}		Date DateOnly `json:"date"`		Name string   `json:"name"`	type Event struct {	// DateOnly in action	fmt.Println("--- CUSTOM MARSHAL/UNMARSHAL ---")func customMarshalUnmarshal() {}	return nil	*s = val	}		return fmt.Errorf("unknown status: %q", name)	if !ok {	val, ok := statusValues[name]	}		return err	if err := json.Unmarshal(data, &name); err != nil {	var name stringfunc (s *Status) UnmarshalJSON(data []byte) error {}	return json.Marshal(name) // wraps in quotes: "active"	}		return nil, fmt.Errorf("unknown status: %d", s)	if !ok {	name, ok := statusNames[s]func (s Status) MarshalJSON() ([]byte, error) {}	"active": StatusActive, "paused": StatusPaused, "stopped": StatusStopped,var statusValues = map[string]Status{}	StatusActive: "active", StatusPaused: "paused", StatusStopped: "stopped",var statusNames = map[Status]string{)	StatusStopped Status = 3	StatusPaused  Status = 2	StatusActive  Status = 1const (type Status int// ── Enum type with string representation ──}	return nil	d.Time = parsed	}		return fmt.Errorf("DateOnly: cannot parse %q: %w", s, err)	if err != nil {	parsed, err := time.Parse("2006-01-02", s)	}		return nil	if s == "null" {	s := strings.Trim(string(data), `"`)	// Remove quotesfunc (d *DateOnly) UnmarshalJSON(data []byte) error {}	return []byte(formatted), nil	formatted := fmt.Sprintf("%q", d.Format("2006-01-02"))	// Format as "YYYY-MM-DD"func (d DateOnly) MarshalJSON() ([]byte, error) {}	time.Timetype DateOnly struct {// But many APIs use "2024-01-15" or Unix timestamps. Custom marshal handles this.// Go's default JSON time format is RFC 3339: "2024-01-15T10:30:00Z"// ── Custom time format ──// =============================================================================// PART 2: Custom MarshalJSON / UnmarshalJSON// =============================================================================}	fmt.Println()	fmt.Printf("  Embedded struct: %s\n", aData)	// NOT nested: {"title":"...", "Timestamps": {"created_at": ...}}	// Result: {"title":"Go JSON Mastery","created_at":"...","updated_at":"..."}	aData, _ := json.Marshal(a)	}		},			UpdatedAt: time.Date(2024, 6, 15, 0, 0, 0, 0, time.UTC),			CreatedAt: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),		Timestamps: Timestamps{		Title: "Go JSON Mastery",	a := Article{	}		Timestamps          // embedded: fields promoted to Article level		Title string `json:"title"`	type Article struct {	}		UpdatedAt time.Time `json:"updated_at"`		CreatedAt time.Time `json:"created_at"`	type Timestamps struct {	// ─── Embedded structs: field promotion ───		u2.ID, u2.FullName, u2.Email, u2.Balance)	fmt.Printf("  Unmarshaled: ID=%d, Name=%q, Email=%q, Balance=%d\n",	json.Unmarshal([]byte(input), &u2)	var u2 User	input := `{"ID": 1, "full_name": "Test", "EMAIL": "test@x.com", "balance": "500"}`	// Unmarshal with case-insensitive matching	fmt.Printf("  Marshaled:\n  %s\n", data)	data, _ := json.MarshalIndent(u, "  ", "  ")	}		Age:      &age, // NOT omitted even though 0, because pointer is non-nil		Email:    "v@test.com",		Password: "secret123", // will NOT appear in JSON		Balance:  999,		Nickname: "", // will be omitted (omitempty)		FullName: "Vikram",		ID:       12345678901234,	u := User{	age := 0	}		Age *int `json:"age,omitempty"`		// Pointer + omitempty: omits when nil (not when zero value)		Email string		// but JSON keys are matched case-insensitively on unmarshal!)		// No tag: uses Go field name as JSON key (case-sensitive on unmarshal,		Password string `json:"-"`		// Hyphen: completely ignored by JSON encoder/decoder		Balance int64 `json:"balance,string"`		// Useful for JavaScript (can't handle int64 precisely)		// String option: number marshaled as JSON string "123"		Nickname string `json:"nickname,omitempty"`		// Omitempty: won't appear in JSON if empty string		FullName string `json:"full_name"`		// Different JSON key name		ID int64 `json:"id"`		// Standard: Go name → JSON key	type User struct {	// ",inline"        → NOT a tag; use embedded struct instead	// ",string"        → marshal number/bool as JSON string ("123" not 123)	// "-"              → NEVER marshal/unmarshal this field	// "name,omitempty" → omit if zero value (0, "", nil, false, empty slice/map)	// "name"           → JSON key name	// ────────	// OPTIONS:	//	// STRUCT TAG FORMAT: `json:"name,options"`	fmt.Println("--- STRUCT TAGS DEEP DIVE ---")func structTagsDeepDive() {// =============================================================================// PART 1: Struct Tags Deep Dive// =============================================================================}	performanceTips()	commonPitfalls()	polymorphicJSON()	jsonNumberPrecision()	streamingJSON()	rawMessagePatterns()	customMarshalUnmarshal()	structTagsDeepDive()	fmt.Println()	fmt.Println("=== JSON MASTERY ===")func main() {)	"time"	"strings"	"io"	"fmt"	"errors"	"encoding/json"	"bytes"import (package main// =============================================================================// RUN: go run 02_json_mastery.go//// around nil, zero values, and embedded structs.// minimize work. For correctness, you need to understand the exact rules// to understand what triggers allocations and how to structure types to// encoding/json uses reflection, which has a cost. For hot paths, you need// THE KEY INSIGHT://// - Common pitfalls (nil vs empty slice, time formats, embedded structs)// - Performance: avoiding reflection, pooling, pre-allocation// - Handling unknown fields, polymorphic JSON, API versioning// - json.Number for precision-sensitive numbers// - Streaming: json.Decoder and json.Encoder (for huge payloads)// - json.RawMessage for partial/lazy parsing// - Custom MarshalJSON / UnmarshalJSON// - Struct tags deep dive (omitempty, string, "-")// WHAT YOU'LL LEARN://// =============================================================================// LESSON 15.2: encoding/json — From Basics to Battle-Tested Production Patterns// =============================================================================//go:build ignore