// =============================================================================
// LESSON 9: CODE GENERATION & AST MANIPULATION
// =============================================================================
//
// Go's toolchain includes powerful code analysis and generation capabilities:
//   - go/ast, go/parser, go/printer — Parse, analyze, transform Go source
//   - go/types — Type checking
//   - go generate — Run code generators
//   - text/template — Generate code from templates
//
// USED BY: stringer, mockgen, protobuf, ent, sqlc, wire (DI)
// =============================================================================

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"text/template"
)

// =============================================================================
// PART 1: Parsing Go Source Code
// =============================================================================

func demonstrateParsing() {
	fmt.Println("=== Parsing Go Source Code ===")

	src := `
package example

import "fmt"

// User represents a user in the system.
type User struct {
	ID    int64
	Name  string
	Email string
}

func (u *User) Greet() string {
	return fmt.Sprintf("Hello, %s!", u.Name)
}

func NewUser(name, email string) *User {
	return &User{Name: name, Email: email}
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "example.go", src, parser.ParseComments)
	if err != nil {
		fmt.Printf("Parse error: %v\n", err)
		return
	}

	// Walk the AST
	fmt.Printf("Package: %s\n", file.Name.Name)
	fmt.Printf("Imports: ")
	for _, imp := range file.Imports {
		fmt.Printf("%s ", imp.Path.Value)
	}
	fmt.Println()

	// Find all type declarations
	fmt.Println("\nType declarations:")
	ast.Inspect(file, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.TypeSpec:
			fmt.Printf("  type %s\n", x.Name.Name)
			if st, ok := x.Type.(*ast.StructType); ok {
				for _, field := range st.Fields.List {
					for _, name := range field.Names {
						fmt.Printf("    field: %s %s\n", name.Name, formatNode(fset, field.Type))
					}
				}
			}
		case *ast.FuncDecl:
			recv := ""
			if x.Recv != nil && len(x.Recv.List) > 0 {
				recv = fmt.Sprintf("(%s) ", formatNode(fset, x.Recv.List[0].Type))
			}
			fmt.Printf("  func %s%s(", recv, x.Name.Name)
			if x.Type.Params != nil {
				params := []string{}
				for _, p := range x.Type.Params.List {
					for _, name := range p.Names {
						params = append(params, fmt.Sprintf("%s %s", name.Name, formatNode(fset, p.Type)))
					}
				}
				fmt.Print(strings.Join(params, ", "))
			}
			fmt.Print(")")
			if x.Type.Results != nil {
				fmt.Printf(" %s", formatNode(fset, x.Type.Results))
			}
			fmt.Println()
		}
		return true
	})
}

func formatNode(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	format.Node(&buf, fset, node)
	return buf.String()
}

// =============================================================================
// PART 2: AST Transformation — Rewriting code programmatically
// =============================================================================

func demonstrateTransformation() {
	fmt.Println("\n=== AST Transformation ===")

	src := `
package example

func add(a, b int) int {
	return a + b
}

func multiply(a, b int) int {
	return a * b
}
`

	fset := token.NewFileSet()
	file, _ := parser.ParseFile(fset, "example.go", src, parser.ParseComments)

	// Transform: Add logging to every function
	ast.Inspect(file, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok {
			return true
		}

		// Create a log statement: fmt.Println("entering <funcname>")
		logStmt := &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   ast.NewIdent("fmt"),
					Sel: ast.NewIdent("Println"),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.STRING,
						Value: fmt.Sprintf(`"entering %s"`, fn.Name.Name),
					},
				},
			},
		}

		// Prepend the log statement to the function body
		fn.Body.List = append([]ast.Stmt{logStmt}, fn.Body.List...)
		return true
	})

	// Print the transformed code
	var buf bytes.Buffer
	format.Node(&buf, fset, file)
	fmt.Println("Transformed code:")
	fmt.Println(buf.String())
}

// =============================================================================
// PART 3: Code Generation with Templates
// =============================================================================

const enumTemplate = `// Code generated by enum-gen; DO NOT EDIT.

package {{.Package}}

import "fmt"

type {{.TypeName}} int

const (
{{- range $i, $v := .Values}}
	{{$.TypeName}}{{$v}} {{$.TypeName}} = {{$i}}
{{- end}}
)

var _{{.TypeName}}Names = map[{{.TypeName}}]string{
{{- range $i, $v := .Values}}
	{{$.TypeName}}{{$v}}: "{{$v}}",
{{- end}}
}

func (e {{.TypeName}}) String() string {
	if name, ok := _{{.TypeName}}Names[e]; ok {
		return name
	}
	return fmt.Sprintf("{{.TypeName}}(%d)", int(e))
}

func Parse{{.TypeName}}(s string) ({{.TypeName}}, error) {
	for k, v := range _{{.TypeName}}Names {
		if v == s {
			return k, nil
		}
	}
	return 0, fmt.Errorf("invalid {{.TypeName}}: %q", s)
}

func (e {{.TypeName}}) IsValid() bool {
	_, ok := _{{.TypeName}}Names[e]
	return ok
}
`

type EnumDef struct {
	Package  string
	TypeName string
	Values   []string
}

func demonstrateCodeGen() {
	fmt.Println("\n=== Code Generation with Templates ===")

	tmpl, err := template.New("enum").Parse(enumTemplate)
	if err != nil {
		fmt.Printf("Template error: %v\n", err)
		return
	}

	def := EnumDef{
		Package:  "status",
		TypeName: "OrderStatus",
		Values:   []string{"Pending", "Processing", "Shipped", "Delivered", "Cancelled"},
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, def); err != nil {
		fmt.Printf("Execute error: %v\n", err)
		return
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Format error: %v\n", err)
		fmt.Println(buf.String()) // print unformatted
		return
	}

	fmt.Println(string(formatted))
}

// =============================================================================
// PART 4: go generate — Integration with build process
// =============================================================================

// To use go generate, add a directive comment in your source:
//
//go:generate stringer -type=Color
//go:generate mockgen -source=repository.go -destination=mock_repository.go

// Example: Generate enum from a type definition
// //go:generate go run github.com/dmarkham/enumer -type=Status -json -text

type Status int

const (
	StatusActive Status = iota
	StatusInactive
	StatusDeleted
)

// =============================================================================
// PART 5: Building a simple code analyzer
// =============================================================================

func analyzeCode(src string) {
	fmt.Println("\n=== Code Analysis ===")

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "analyze.go", src, parser.ParseComments)
	if err != nil {
		fmt.Printf("Parse error: %v\n", err)
		return
	}

	var issues []string

	ast.Inspect(file, func(n ast.Node) bool {
		switch x := n.(type) {
		// Check for empty function bodies
		case *ast.FuncDecl:
			if x.Body != nil && len(x.Body.List) == 0 {
				pos := fset.Position(x.Pos())
				issues = append(issues,
					fmt.Sprintf("%s:%d: function %s has empty body",
						pos.Filename, pos.Line, x.Name.Name))
			}

		// Check for naked returns in functions with named results
		case *ast.ReturnStmt:
			if len(x.Results) == 0 {
				pos := fset.Position(x.Pos())
				issues = append(issues,
					fmt.Sprintf("%s:%d: naked return (can reduce readability)",
						pos.Filename, pos.Line))
			}

		// Check for TODO comments
		case *ast.Comment:
			if strings.Contains(x.Text, "TODO") || strings.Contains(x.Text, "FIXME") {
				pos := fset.Position(x.Pos())
				issues = append(issues,
					fmt.Sprintf("%s:%d: %s",
						pos.Filename, pos.Line, strings.TrimSpace(x.Text)))
			}
		}
		return true
	})

	if len(issues) == 0 {
		fmt.Println("No issues found!")
	} else {
		fmt.Printf("Found %d issues:\n", len(issues))
		for _, issue := range issues {
			fmt.Printf("  %s\n", issue)
		}
	}
}

func main() {
	demonstrateParsing()
	demonstrateTransformation()
	demonstrateCodeGen()

	// Analyze some code with issues
	analyzeCode(`
package example

// TODO: implement validation
func validate() {
}

func calculate(a, b int) (result int, err error) {
	result = a + b
	// FIXME: handle overflow
	return
}
`)

	// Generate a real file to demonstrate
	fmt.Println("\n=== go:generate Workflow ===")
	fmt.Println("1. Add //go:generate directives to your source files")
	fmt.Println("2. Run: go generate ./...")
	fmt.Println("3. Generated files should have 'Code generated ... DO NOT EDIT' header")
	fmt.Println("4. Commit generated files to version control")
	fmt.Println()
	fmt.Println("Popular generators:")
	fmt.Println("  stringer    — String() methods for int enums")
	fmt.Println("  mockgen     — Interface mocks for testing")
	fmt.Println("  protoc-gen-go — Protocol Buffer code")
	fmt.Println("  sqlc        — Type-safe SQL queries")
	fmt.Println("  wire        — Compile-time dependency injection")
	fmt.Println("  ent         — Entity framework / ORM")

	_ = os.Stdout // use os to avoid unused import
	_ = StatusActive
}
